const tabela2024 = [
  {
    nome: 'Sao Paulo',
    sigla: 'SPO',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: 'Athetico-PR',
    sigla: 'CAP',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: 'Internacional',
    sigla: 'INT',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: 'Athetico-MG',
    sigla: 'CAM',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: 'Botafoga',
    sigla: 'BOT',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: 'Fortaleza',
    sigla: 'FOR',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: 'Gremio',
    sigla: 'GRE',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: 'Bahia',
    sigla: 'BAH',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: 'Palmeiras',
    sigla: 'PAL',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },

  {
    nome: 'Flamengo',
    sigla: 'FLA',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
    saldoGols: 0,
  },
];

export default tabela2024